version: '3'
services:
  softcite:
    image: softcite:latest
    build: .
    ports:
      - "8789:8787"
    volumes:
      - .:/home/rstudio/softcite-dataset
      - ../softcite-pdf-files/:/home/rstudio/softcite-pdf-files
    environment:
      - PASSWORD=rbox
